const seedDB = () => {
  let seed = {
      "Massas e molhos 🍝": [
        "Macarrão",
        "Molho de tomate",
        "Massa de tomate",
        "Miojo",
        "Lasanha",
        "Ravióli",
        "Espaguete",
        "Nhoque",
        "Fettuccine",
        "Talharim",
        "Molho branco",
        "Molho pesto",
        "Molho à bolonhesa",
        "Molho de queijo",
        "Molho de pimenta",
        "Molho de alho",
        "Molho de cogumelos",
        "Molho barbecue",
        "Molho de ervas",
        "Molho de iogurte",
        "Molho de soja",
        "Molho de curry",
        "Molho de amendoim",
        "Molho de mostarda",
        "Molho de tamarindo",
        "Molho de ostra",
        "Molho de peixe",
        "Molho de vinho",
        "Molho de laranja",
        "Molho de abacaxi"
      ],
      "Bebidas 🍷": [
        "Vinho",
        "Cerveja",
        "Coca-Cola",
        "Guarana",
        "Monster",
        "Água",
        "Suco de laranja",
        "Suco de maçã",
        "Suco de uva",
        "Suco de abacaxi",
        "Suco de morango",
        "Suco de maracujá",
        "Suco de manga",
        "Suco de pêssego",
        "Suco de limão",
        "Suco de melancia",
        "Suco de tangerina",
        "Suco de cranberry",
        "Chá verde",
        "Chá preto",
        "Chá de hibisco",
        "Chá de camomila",
        "Chá de menta",
        "Chá de gengibre",
        "Chá de frutas",
        "Chá de erva-cidreira",
        "Chá de canela",
        "Chá de rosa mosqueta",
        "Chá de jasmim"
      ],
      "Açougue 🥩": [
        "Carne bovina",
        "Carne suína",
        "Carne de frango",
        "Carne de peixe",
        "Carne de cordeiro",
        "Filé mignon",
        "Alcatra",
        "Picanha",
        "Costela",
        "Linguiça",
        "Salsicha",
        "Frango inteiro",
        "Peito de frango",
        "Coxa de frango",
        "Sobrecoxa de frango",
        "Asa de frango",
        "Peixe fresco",
        "Peixe congelado",
        "Lombo de porco",
        "Bisteca de porco",
        "Costeleta de porco",
        "Filé de peixe",
        "Filé de frango",
        "Patinho moído",
        "Carne moída",
        "Maminha",
        "Fígado de boi",
        "Fígado de frango",
        "Moela de frango"
      ],
      "Cereais e farináceos 🍚": [
        "Arroz",
        "Feijão",
        "Milho",
        "Aveia",
        "Trigo",
        "Cevada",
        "Quinoa",
        "Cuscuz",
        "Farinha de trigo",
        "Farinha de milho",
        "Farinha de mandioca",
        "Farinha de arroz",
        "Farinha de aveia",
        "Farinha de centeio",
        "Farinha de quinoa",
        "Farinha de amêndoa",
        "Farelo de trigo",
        "Farelo de aveia",
        "Farelo de arroz",
        "Farelo de milho",
        "Farelo de soja",
        "Macarrão integral",
        "Macarrão sem glúten",
        "Macarrão de arroz",
        "Macarrão de milho",
        "Macarrão de quinoa",
        "Macarrão de feijão",
        "Macarrão de batata",
        "Macarrão de trigo sarraceno",
        "Macarrão de espelta"
      ],
      "Enlatados 🥫": [
        "Sardinha em lata",
        "Atum em lata",
        "Milho em conserva",
        "Ervilha em conserva",
        "Feijão em conserva",
        "Tomate pelado",
        "Azeitonas em conserva",
        "Palmito em conserva",
        "Cogumelos em conserva",
        "Molho de tomate enlatado",
        "Leite condensado",
        "Leite em pó",
        "Doce de leite",
        "Creme de leite",
        "Milho verde em lata",
        "Creme de milho",
        "Leite de coco em lata",
        "Achocolatado em pó",
        "Catchup",
        "Maionese",
        "Mostarda",
        "Geleia",
        "Patê",
        "Molho de peixe",
        "Molho de soja",
        "Molho inglês",
        "Molho de pimenta",
        "Molho de alho",
        "Molho de churrasco"
      ],
      "Frios 🧀": [
        "Queijo mussarela",
        "Queijo prato",
        "Queijo cheddar",
        "Queijo parmesão",
        "Queijo provolone",
        "Queijo gorgonzola",
        "Queijo brie",
        "Queijo camembert",
        "Queijo roquefort",
        "Queijo cottage",
        "Presunto",
        "Peito de peru",
        "Salame",
        "Linguiça defumada",
        "Salsicha",
        "Bacon",
        "Mortadela",
        "Pastrami",
        "Rosbife",
        "Copa",
        "Salaminho",
        "Pepperoni",
        "Queijo suíço",
        "Queijo minas",
        "Queijo coalho",
        "Queijo ricota",
        "Requeijão cremoso",
        "Iogurte natural",
        "Iogurte saborizado",
        "Creme de ricota"
      ],
      "Laticíneos 🥛": [
        "Leite integral",
        "Leite desnatado",
        "Leite semidesnatado",
        "Leite de cabra",
        "Leite de soja",
        "Leite de amêndoa",
        "Leite de arroz",
        "Leite de aveia",
        "Iogurte natural",
        "Iogurte saborizado",
        "Manteiga",
        "Margarina",
        "Queijo cottage",
        "Queijo cheddar",
        "Queijo prato",
        "Queijo minas",
        "Queijo muçarela",
        "Queijo parmesão",
        "Queijo gorgonzola",
        "Requeijão cremoso",
        "Creme de leite",
        "Iogurte grego",
        "Iogurte de frutas",
        "Iogurte batido",
        "Iogurte probiótico",
        "Iogurte vegano",
        "Nata",
        "Coalhada"
      ],
      "Material de limpeza 🧼": [
        "Sabão em pó",
        "Sabão líquido",
        "Amaciante de roupas",
        "Detergente",
        "Desinfetante",
        "Limpador multiuso",
        "Limpador de vidros",
        "Limpador de banheiro",
        "Limpador de cozinha",
        "Limpador de piso",
        "Limpador de carpete",
        "Água sanitária",
        "Álcool em gel",
        "Álcool líquido",
        "Panos de limpeza",
        "Esponjas",
        "Vassoura",
        "Rodo",
        "Balde",
        "Luvas de limpeza",
        "Escova",
        "Saco de lixo",
        "Inseticida",
        "Repelente",
        "Limpa-vidros",
        "Odorizador de ambiente",
        "Papel toalha",
        "Papel higiênico",
        "Toalha de papel"
      ],
      "Higiene pessoal 🧻": [
        "Sabonete",
        "Shampoo",
        "Condicionador",
        "Creme hidratante",
        "Loção corporal",
        "Desodorante",
        "Pasta de dente",
        "Escova de dentes",
        "Fio dental",
        "Enxaguante bucal",
        "Absorvente",
        "Protetor diário",
        "Protetor solar",
        "Creme para barbear",
        "Lâminas de barbear",
        "Papel higiênico",
        "Lenços umedecidos",
        "Algodão",
        "Cotonetes",
        "Hastes flexíveis",
        "Desodorante íntimo",
        "Sabonete íntimo",
        "Creme depilatório",
        "Sabonete líquido",
        "Espuma de barbear",
        "Gel de banho",
        "Óleo corporal",
        "Gel dental"
      ],
      "Peixaria 🍤": [
        "Peixe fresco",
        "Peixe congelado",
        "Camarão",
        "Salmão",
        "Atum",
        "Tilápia",
        "Bacalhau",
        "Lula",
        "Polvo",
        "Mexilhões",
        "Mariscos",
        "Caranguejo",
        "Ostras",
        "Truta",
        "Robalo",
        "Pescada",
        "Linguado",
        "Dourado",
        "Bagre",
        "Tainha",
        "Sardinha",
        "Anchova",
        "Cavala",
        "Peixe-espada",
        "Lagosta",
        "Cação",
        "Enguia",
        "Tamboril",
        "Abadejo"
      ],
      "Hortifrúti (frutas e verduras) 🥦": [
        "Maçã",
        "Banana",
        "Laranja",
        "Limão",
        "Abacaxi",
        "Melancia",
        "Uva",
        "Morango",
        "Manga",
        "Pêssego",
        "Pera",
        "Cereja",
        "Ameixa",
        "Kiwi",
        "Maracujá",
        "Goiaba",
        "Caju",
        "Melão",
        "Caqui",
        "Tangerina",
        "Abacate",
        "Acerola",
        "Jabuticaba",
        "Pitanga",
        "Figo",
        "Amora",
        "Physalis",
        "Mirtilo",
        "Fruta-pão"
      ],
      "Padaria 🍞": [
        "Pão francês",
        "Pão de forma",
        "Pão integral",
        "Pão de centeio",
        "Pão de milho",
        "Pão de queijo",
        "Pão de batata",
        "Pão sírio",
        "Pão de hambúrguer",
        "Pão de hot dog",
        "Baguete",
        "Croissant",
        "Brioche",
        "Rosca",
        "Bolacha",
        "Torrada",
        "Bolo de chocolate",
        "Bolo de cenoura",
        "Bolo de fubá",
        "Bolo de milho",
        "Bolo de laranja",
        "Bolo de coco",
        "Bolo de limão",
        "Bolo de banana",
        "Bolo de morango",
        "Bolo de abacaxi",
        "Bolo de maracujá",
        "Bolo de maçã",
        "Bolo de amendoim"
      ],
      "Produtos pet 🐶": [
        "Ração para cães",
        "Ração para gatos",
        "Petiscos para cães",
        "Petiscos para gatos",
        "Areia para gatos",
        "Tapete higiênico para cães",
        "Caixa de transporte",
        "Coleira",
        "Guia",
        "Brinquedos para cães",
        "Brinquedos para gatos",
        "Cama para cães",
        "Cama para gatos",
        "Escova para pelos",
        "Shampoo para cães",
        "Shampoo para gatos",
        "Condicionador para cães",
        "Condicionador para gatos",
        "Antipulgas",
        "Anticarrapatos",
        "Coleira antiparasitária",
        "Suplementos vitamínicos",
        "Tigelas de comida e água",
        "Caixa de areia",
        "Arranhadores",
        "Coleira antilatido",
        "Gaiola para pássaros",
        "Aquário",
        "Comedouros",
        "Bebedouros"
      ],
      "Utensílios para cozinha 🍴": [
        "Panelas",
        "Frigideiras",
        "Facas",
        "Conjunto de talheres",
        "Pratos",
        "Copos",
        "Taças",
        "Xícaras",
        "Potes de armazenamento",
        "Formas para bolo",
        "Formas para pizza",
        "Assadeiras",
        "Liquidificadores",
        "Batedeiras",
        "Espremedores de frutas",
        "Raladores",
        "Tábuas de corte",
        "Abridores de lata",
        "Espremedores de alho",
        "Descascadores",
        "Colheres de pau",
        "Conchas",
        "Escumadeiras",
        "Peneiras",
        "Espátulas",
        "Garrafas térmicas",
        "Frigobares",
        "Torradeiras",
        "Máquinas de café",
        "Fornos elétricos",
        "Liquidificadores portáteis"
      ],
      "Congelados 🍨": [
        "Pizza",
        "Lasanha",
        "Hambúrguer",
        "Coxinha",
        "Empanada",
        "Nuggets de frango",
        "Batata frita congelada",
        "Legumes congelados",
        "Frutas congeladas",
        "Sorvetes",
        "Picolés",
        "Sorbet",
        "Sorvete de massa",
        "Sorvete de frutas",
        "Sorvete vegano",
        "Sorvete sem lactose",
        "Sorvete sem açúcar",
        "Sorvete diet",
        "Massa folhada",
        "Massa de pizza",
        "Massa de torta",
        "Massa de pastel",
        "Massa de coxinha",
        "Massa de empada",
        "Massa de lasanha",
        "Massa de crepe",
        "Massa de canelone",
        "Massa de ravióli",
        "Massa de nhoque",
        "Massa de panqueca"
      ],
      "Material escolar 📓": [
        "Cadernos",
        "Lápis",
        "Canetas",
        "Borrachas",
        "Apontadores",
        "Estojos",
        "Réguas",
        "Tesouras",
        "Colas",
        "Marcadores",
        "Lápis de cor",
        "Giz de cera",
        "Tintas",
        "Pincéis",
        "Cadernos de desenho",
        "Agendas",
        "Mochilas",
        "Lancheiras",
        "Pastas",
        "Fichários",
        "Papel sulfite",
        "Bloco de notas",
        "Dicionários",
        "Calculadoras",
        "Compassos",
        "Transferidores",
        "Bússolas",
        "Estojos de geometria",
        "Livros didáticos",
        "Livros de literatura"
      ],
    
    "Eletrônicos 💻": [
      "Smartwatches",
      "Fones de ouvido sem fio",
      "Carregadores portáteis",
      "Câmeras de segurança",
      "Assistentes virtuais",
      "Smart TVs",
      "Home theaters",
      "Projetores",
      "Câmeras de ação",
      "Rádios portáteis",
      "Caixas de som Bluetooth",
      "Auriculares",
      "Microfones",
      "Placas de vídeo",
      "Processadores",
      "Memórias RAM",
      "HDs externos",
      "SSDs",
      "Cabos de energia",
      "Adaptadores de energia",
      "Estabilizadores de tensão",
      "Estabilizadores de câmera",
      "Cartões de memória",
      "Carregadores de celular",
      "Baterias externas",
      "Webcams",
      "Mousepads",
      "Monitores gamer",
      "Teclados mecânicos"
      ],
      "Perfumaria e loções 🧴": [
      "Perfumes masculinos",
      "Perfumes femininos",
      "Perfumes unissex",
      "Perfumes infantis",
      "Colônias",
      "Desodorantes",
      "Loções corporais",
      "Cremes hidratantes",
      "Óleos corporais",
      "Óleos essenciais",
      "Águas de colônia",
      "Águas perfumadas",
      "Desodorantes sem perfume",
      "Desodorantes antitranspirantes",
      "Desodorantes roll-on",
      "Desodorantes em spray",
      "Desodorantes em creme",
      "Desodorantes em barra",
      "Desodorantes aerosol",
      "Gel pós-barba",
      "Loções pós-barba",
      "Cremes de barbear",
      "Gel de banho perfumado",
      "Sabonetes líquidos",
      "Sabonetes em barra",
      "Sabonetes íntimos",
      "Sabonetes antissépticos",
      "Desodorantes íntimos",
      "Álcool perfumado"
      ]
  };
  let users = [
    {
      id: 1,
      name: 'Paulo Silveira',
      username: 'p@ul0',
      email: 'paulo.sv@email.com',
      password: '1234',
      lists: ['#7818L'],
      colabLists: []
    },
    {
      id: 2,
      name: 'Luana Silveira',
      username: 'lana_',
      email: 'luana.sv@email.com',
      password: 'luana1',
      lists: [],
      colabLists: ['#7818L']
    }
  ]
  let lists = [
    {
      title: 'Lista_24/06',
      id: '#7818L',
      updated_date: '24/6/2023 14:14',
      ownerID: 1,
      sections: [
        {
          section: 'Hortifrúti (frutas e verduras) 🥦',
          id: 1,
          products: ['Maçã', 'Banana', 'Laranja'],
        },
        {
          section: 'Padaria 🍞',
          id: 2,
          products: ["Pão de milho", "Pão de queijo", "Pão de batata"]
        }
      ]
    }
  ]
  localStorage.setItem("produtos", JSON.stringify(seed));
  localStorage.setItem("users", JSON.stringify(users))
  localStorage.setItem("lists", JSON.stringify(lists))
}
const seed = () =>{
  if(!localStorage.getItem('users')){
    seedDB();
  }
}
seed();